<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Invoice {{ $sale->sale_number }}</title>
  <style>
    body { font-family: Arial, sans-serif; color:#111; }
    .container { max-width: 900px; margin: 0 auto; padding: 24px; }
    .header { display:flex; justify-content: space-between; align-items:flex-start; }
    .company h2 { margin:0 0 4px; }
    .meta { text-align:right; }
    table { width:100%; border-collapse: collapse; margin-top: 16px; }
    th, td { border:1px solid #ddd; padding:8px; }
    th { background:#f7f7f7; text-align:left; }
    tfoot th { text-align:right; }
    .text-right { text-align:right; }
    .muted { color:#666; font-size:12px; }
    @page { margin: 20mm; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="company">
        <h2>Invoice</h2>
        <div class="muted">Generated by EquiServe</div>
      </div>
      <div class="meta">
        <div><strong>Sale #:</strong> {{ $sale->sale_number }}</div>
        <div><strong>Date:</strong> {{ $sale->created_at->format('Y-m-d H:i') }}</div>
      </div>
    </div>

    <div style="margin-top:16px; display:flex; justify-content: space-between;">
      <div>
        <h4 style="margin:0 0 8px;">Billed To</h4>
        <div>{{ $sale->customer->full_name ?? '-' }}</div>
        <div class="muted">{{ $sale->customer->contact ?? '' }}</div>
      </div>
      <div style="text-align:right;">
        <h4 style="margin:0 0 8px;">Payment</h4>
        <div><strong>Mode:</strong> {{ $sale->payment_mode ? ucfirst($sale->payment_mode) : '-' }}</div>
        @if ($sale->payment_mode==='cash')
          <div><strong>Amount Tendered:</strong> {{ $sale->amount_tendered ? number_format($sale->amount_tendered,2) : '-' }}</div>
        @elseif ($sale->payment_mode==='online')
          @if($sale->payment_bank)
            <div><strong>Bank/Platform:</strong> {{ $sale->payment_bank }}</div>
          @endif
          <div><strong>Reference #:</strong> {{ $sale->reference_number ?? '-' }}</div>
          @if($sale->payment_timestamp)
            <div><strong>Payment Time:</strong> {{ \Carbon\Carbon::parse($sale->payment_timestamp)->format('M d, Y h:i A') }}</div>
          @endif
        @endif
      </div>
    </div>

    <table>
      <thead>
        <tr>
          <th>Product</th>
          <th class="text-right">Qty</th>
          <th class="text-right">Unit Price</th>
          <th class="text-right">Subtotal</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($sale->items as $item)
          <tr>
            <td>{{ $item->product->name ?? ('#'.$item->product_id) }}</td>
            <td class="text-right">{{ $item->quantity }}</td>
            <td class="text-right">{{ number_format($item->unit_price, 2) }}</td>
            <td class="text-right">{{ number_format($item->subtotal, 2) }}</td>
          </tr>
        @endforeach
      </tbody>
      <tfoot>
        @if ($sale->discount_total)
        <tr>
          <th colspan="3">Discount</th>
          <th class="text-right">-{{ number_format($sale->discount_total, 2) }}</th>
        </tr>
        @endif
        <tr>
          <th colspan="3">Total</th>
          <th class="text-right">{{ number_format($sale->total_amount, 2) }}</th>
        </tr>
      </tfoot>
    </table>

    <p class="muted" style="margin-top:24px;">This document is generated for download and standard printing (A4). No thermal receipt support.</p>
  </div>
</body>
</html>
